from typing import List, Tuple


import numpy as np
import torch
from torch.nn import Module
from transformers.cache_utils import DynamicCache
from vllm import SamplingParams, LLM
from vllm.inputs.data import TokensPrompt

from progen.utils import LogitsProcessor, GreedyProcessor, prune_cache
import progen.printing_utils as printing


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


@torch.no_grad()
def speculative_generate(
    inputs: List[int],
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 512,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)

    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): whether to skip the sample adjustment step when some drafts are discarded.
        first_target (bool): whether to run the target model before the speculative algorithm.
        debug (bool): debug mode.

    Returns:
        List[int]: generated sequence.
        float: acceptance rate (number of accepted drafts divided by the number of total drafts).

    Note: This generation methods only works for decoder-only models.
    Note bis: The drafter and target models should output the same logits shape.
    Note ter: NgramModels are currently not supported.
    """

    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)

    drafts_accepted, drafts_speculated = .0, .0

    vocabulary_size = target.config.vocab_size

    # prepare input tensor
    prompt_len = len(inputs)
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = inputs

    current_position = prompt_len

    if first_target:
        # run the target model before the speculative algorithm. Allows to prefill the kvcache and get a first token.
        Mp = target(
            input_ids=input_ids[..., :current_position],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        p_p = logits_processor(Mp.logits[..., -1, :])
        t = logits_processor.sample(p_p)
        input_ids[0, current_position] = t
        current_position += 1

        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return input_ids[0, prompt_len:current_position].tolist(), 0

        if debug:
            printing.initial_step(t, tokenizer)

    while current_position < total_len:
        # initialize current "block" to be produced by the drafter
        corrected_gamma = min(gamma, total_len - current_position - 1)
        q = torch.zeros((1, corrected_gamma, vocabulary_size), device=target.device)

        input_ids = input_ids.to(drafter.device)

        # generate gamma drafts
        for k in range(corrected_gamma):
            Mq = drafter(
                input_ids=input_ids[..., :current_position + k],
                past_key_values=drafter_cache,
                use_cache=use_cache,
            )
            # KV cache for drdafter
            drafter_cache = Mq.past_key_values

            # get probabilities for M_q
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = logits_processor(draft_logits)
            q[0, k] = draft_probs.to(target.device)

            # perform sampling on drafter model
            xi = logits_processor.sample(draft_probs)
            input_ids[0, current_position + k] = xi

        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)

        # run target model on drafts and get logits of the previous tokens plus one more token
        Mp = target(
            input_ids=input_ids[..., :current_position + corrected_gamma],
            past_key_values=target_cache,
            use_cache=use_cache,
        )

        # kv cache for M_p (target model)
        target_cache = Mp.past_key_values

        # get probabilities for M_p
        draft_logits = Mp.logits[..., current_position - 1:current_position + corrected_gamma - 1, :] # [1, corrected_gamma, vocab_size]
        p = logits_processor(draft_logits) # [1, gamma, vocab_size]

        # compute the last accepted draft position (rejection sampling)
        r = torch.rand(corrected_gamma, device=target.device)
        fractions = p / q
        n = corrected_gamma

        # reject if r > frac; n is the number of accepted guesses.
        for i in range(corrected_gamma):
            if r[i] > fractions[0, i, input_ids[0, current_position + i]]:
                n = i
                break

        drafts_accepted += n

        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return input_ids[0, prompt_len:current_position + stop_location + 1].tolist(), drafts_accepted / drafts_speculated

        # adjust the distribution from Mp
        if n == corrected_gamma:
            p_p = Mp.logits[..., current_position + corrected_gamma - 1, :]
            p_p = logits_processor(p_p)
        else:
            # prune the cache
            if use_cache:
                drafter_cache = prune_cache(drafter_cache, corrected_gamma - n)
                target_cache = prune_cache(target_cache, corrected_gamma - n + 1)

            if not skip_sample_adjustment:
                p_p = max_fn(p[..., n, :] - q[0, n, :])
            else:
                p_p = p[..., n, :]
        x = logits_processor.sample(p_p)

        if debug:
            generated = input_ids.clone().detach()

        input_ids[0, current_position + n:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + n] = x

        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)

        current_position += n + 1

        if torch.isin(x, stop_tokens):
            if debug:
                printing.end_token_found(n)
            return input_ids[0, prompt_len:current_position].tolist(), drafts_accepted / drafts_speculated

    return input_ids[0, prompt_len:].tolist(), drafts_accepted / drafts_speculated


def get_probs_vllm(llm: LLM, input_ids, max_tokens, temp, vocab_size, ret_prompt_logprobs=False):
    # Set prompt_logprobs=0 to only compute the logprobs of the prompt tokens.
    # Set max_tokens=1 to only generate one token for speed.
    sampling_params = SamplingParams(n=1, max_tokens=max_tokens, temperature=temp, prompt_logprobs=20, logprobs=20)

    tokens_prompt = TokensPrompt(prompt_token_ids=input_ids)

    outputs = llm.generate(tokens_prompt, sampling_params)
    # There should only be one output sequence.
    assert len(outputs) == 1
    assert len(outputs[0].outputs) == 1
    output = outputs[0].outputs[0]
    num_tokens_generated = len(output.token_ids)
    assert num_tokens_generated == max_tokens, f"num_tokens_generated={num_tokens_generated}, max_tokens={max_tokens}"

    gen_probs = torch.ones((num_tokens_generated, vocab_size)) * 1e-6
    # Each subsequent logprob is a dict of length 1 where the key is the token ID and
    # the value is a Logprob object.
    for i, token_id_to_logprob in enumerate(output.logprobs):
        for token_id, logprob in token_id_to_logprob.items():
            gen_probs[i][token_id] = np.exp(logprob.logprob)

    gen_probs = gen_probs / gen_probs.sum(dim=-1, keepdim=True)

    if ret_prompt_logprobs:
        prompt_probs = torch.ones((len(outputs[0].prompt_logprobs) - 1, vocab_size)) * 1e-6
        # Each subsequent logprob is a dict of length 1 where the key is the token ID and
        # the value is a Logprob object.
        for i, token_id_to_logprob in enumerate(outputs[0].prompt_logprobs[1:]):
            for token_id, logprob in token_id_to_logprob.items():
                prompt_probs[i][token_id] = np.exp(logprob.logprob)

        prompt_probs = prompt_probs / prompt_probs.sum(dim=-1, keepdim=True)
    else:
        prompt_probs = None

    return gen_probs, prompt_probs, output


def speculative_generate_vllm(
    inputs: List[int],
    drafter: Module,
    target: Module,
    device="cuda",
    gamma: int = 5,
    temp: float = 0.2,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 512,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = None,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)

    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): whether to skip the sample adjustment step when some drafts are discarded.
        first_target (bool): whether to run the target model before the speculative algorithm.
        debug (bool): debug mode.

    Returns:
        List[int]: generated sequence.
        float: acceptance rate (number of accepted drafts divided by the number of total drafts).

    Note: This generation methods only works for decoder-only models.
    Note bis: The drafter and target models should output the same logits shape.
    Note ter: NgramModels are currently not supported.
    """
    tokenizer = target.get_tokenizer()

    target_sampling_params = SamplingParams(
        n=1,
        temperature=temp,
        max_tokens=1,
    )

    if eos_tokens_id is None:
        eos_tokens_id = tokenizer.encode("<|eos|>")[0]
    if pad_token_id is None:
        pad_token_id = tokenizer.encode("<|pad|>")[0]

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=device).unsqueeze(1)

    drafts_accepted, drafts_speculated = .0, .0

    vocabulary_size = tokenizer.vocab_size

    # prepare input tensor
    prompt_len = len(inputs)
    # TODO: This is a hack to get the max_seq_length.
    max_seq_length = 1024
    # max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)

    inputs = torch.tensor(tokenizer.encode(inputs), dtype=torch.long, device=device)
    input_ids = torch.full((total_len,), pad_token_id, dtype=torch.long, device=device)
    input_ids[:prompt_len] = inputs

    current_position = prompt_len

    if first_target:
        # run the target model before the speculative algorithm. Allows to prefill the kvcache and get a first token.

        t = target.generate(
            TokensPrompt(prompt_token_ids=input_ids[..., :current_position]),
            target_sampling_params,
        )
        assert len(t) == 1
        assert len(t[0].outputs) == 1
        assert len(t[0].outputs[0].token_ids) == 1
        t = t[0].outputs[0].token_ids[0]
        input_ids[current_position] = t
        current_position += 1

        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return input_ids[prompt_len:current_position].tolist(), 0

        if debug:
            printing.initial_step(t, tokenizer)

    while current_position < total_len:
        # initialize current "block" to be produced by the drafter
        # TODO: should this be total_len - current_position - 1 like in the original implementation?
        corrected_gamma = min(gamma, total_len - current_position)
        # q = torch.zeros((corrected_gamma, vocabulary_size), device=device)

        input_ids = input_ids.to(device)

        if corrected_gamma <= 0:
            breakpoint()
        # generate gamma drafts
        draft_probs, _, draft_output = get_probs_vllm(drafter, input_ids[:current_position], corrected_gamma, temp, vocabulary_size)
        q = draft_probs
        drafts_speculated += corrected_gamma
        input_ids[current_position : current_position + corrected_gamma] = torch.tensor(
            draft_output.token_ids
        ).to(device)

        # run target model on drafts and get logits of the previous tokens plus one more token
        target_gen_probs, target_prompt_probs, target_output = get_probs_vllm( target, input_ids[:current_position + corrected_gamma], 1, temp, vocabulary_size, ret_prompt_logprobs=True )

        # get probabilities for M_p
        # TODO: check if the indexing should be -1 or -2
        # p = target_prompt_probs[..., current_position - 1:current_position + corrected_gamma - 1, :] # [1, corrected_gamma, vocab_size]
        p = target_prompt_probs[..., current_position - 2:current_position + corrected_gamma - 2, :] # [1, corrected_gamma, vocab_size]

        # compute the last accepted draft position (rejection sampling)
        r = torch.rand(corrected_gamma, device=device)
        fractions = p / q
        n = corrected_gamma

        # reject if r > frac; n is the number of accepted guesses.
        for i in range(corrected_gamma):
            if r[i] > fractions[i, input_ids[current_position + i]]:
                n = i
                break

        drafts_accepted += n

        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return input_ids[prompt_len:current_position + stop_location + 1].tolist(), drafts_accepted / drafts_speculated

        # TODO: check if this is correct
        # Only adjust the distribution from Mp if we are not at the last position.
        if current_position < total_len - 1:
            # adjust the distribution from Mp
            if n == corrected_gamma:
                # TODO: check if the indexing should be -1 or -2
                p_p = target_prompt_probs[current_position + corrected_gamma - 2, :]
            else:
                if not skip_sample_adjustment:
                    p_p = max_fn(p[n, :] - q[n, :])
                else:
                    p_p = p[n, :]
            x = logits_processor.sample(p_p)

            if debug:
                generated = input_ids.clone().detach()

            input_ids[current_position + n:current_position + corrected_gamma] = pad_token_id
            input_ids[current_position + n] = x

        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)

        current_position += n + 1

        if torch.isin(x.to(stop_tokens.device), stop_tokens):
            if debug:
                printing.end_token_found(n)
            return input_ids[prompt_len:current_position].tolist(), drafts_accepted / drafts_speculated

    return input_ids[prompt_len:].tolist(), drafts_accepted / drafts_speculated
